// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
  );
  static const String _webAppId = String.fromEnvironment(
    'FIREBASE_WEB_APP_ID',
  );
  static const String _webMessagingSenderId = String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
  );
  static const String _webProjectId = String.fromEnvironment(
    'FIREBASE_PROJECT_ID',
  );
  static const String _webStorageBucket = String.fromEnvironment(
    'FIREBASE_STORAGE_BUCKET',
  );
  static const String _webAuthDomain = String.fromEnvironment(
    'FIREBASE_AUTH_DOMAIN',
  );
  static const String _webMeasurementId = String.fromEnvironment(
    'FIREBASE_MEASUREMENT_ID',
  );

  static bool get isWebConfigured =>
      _webApiKey.isNotEmpty &&
      _webAppId.isNotEmpty &&
      _webMessagingSenderId.isNotEmpty &&
      _webProjectId.isNotEmpty;

  static FirebaseOptions? get currentPlatformOrNull {
    if (kIsWeb) {
      return isWebConfigured ? web : null;
    }
    return currentPlatform;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Iu9w-2d52shEIbI12UpLjh_i7qDlc_A',
    appId: '1:1064671521089:android:7c9f327c5181b692d719c0',
    messagingSenderId: '1064671521089',
    projectId: 'echo-loop-20260310',
    storageBucket: 'echo-loop-20260310.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: _webAppId,
    messagingSenderId: _webMessagingSenderId,
    projectId: _webProjectId,
    authDomain: _webAuthDomain,
    storageBucket: _webStorageBucket,
    measurementId: _webMeasurementId,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHnkLgxESaiAo_ohHYyxYanjSbpwwtqrs',
    appId: '1:1064671521089:ios:c16ecec85ba16296d719c0',
    messagingSenderId: '1064671521089',
    projectId: 'echo-loop-20260310',
    storageBucket: 'echo-loop-20260310.firebasestorage.app',
    iosBundleId: 'top.echo-loop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHnkLgxESaiAo_ohHYyxYanjSbpwwtqrs',
    appId: '1:1064671521089:ios:c16ecec85ba16296d719c0',
    messagingSenderId: '1064671521089',
    projectId: 'echo-loop-20260310',
    storageBucket: 'echo-loop-20260310.firebasestorage.app',
    iosBundleId: 'top.echo-loop',
  );
}
